#!/bin/bash
# @Author  : Zhang Chen
# @Email    : zhangchen.shaanxi@gmail.com
# @File    : vmi-server
# This script will be add to /etc/init.d/
# chkconfig: 345 99 01
# description: vmi-server
case $1 in
start)
    echo "Starting vmi-server"
    cd /root/vmi-server
    ./startup.sh
    ;;
stop)
    echo "Starting vmi-server"
    cd /root/vmi-server
    ./shutdown.sh
    ;;
restart)
    echo "Restarting vmi-server"
    cd /root/vmi-server
    ./shutdown.sh
    ./startup.sh
    ;;
*)
    ;;
esac

